const lessonTitle = "我们一样爱他们";

const lessonData = [
    // ===== 第 1 段 =====
    ["天堂村小学", "tiān táng cūn xiǎo xué", "Tiantang Village Primary School", "Sekolah Rendah Kampung Tiantang"],
    ["地处", "dì chǔ", "located in", "terletak di"],
    ["偏远", "piān yuǎn", "remote", "terpencil"],
    ["山区", "shān qū", "mountainous area", "kawasan pergunungan"],
    ["，", "", "", ""],
    ["交通", "jiāo tōng", "transportation", "pengangkutan"],
    ["不便", "bù biàn", "inconvenient", "tidak selesa"],
    ["，", "", "", ""],
    ["偶尔", "ǒu ěr", "occasionally", "kadang-kadang"],
    ["才", "cái", "only", "baru"],
    ["有", "yǒu", "there are", "ada"],
    ["慈善家", "cí shàn jiā", "philanthropists", "dermawan"],
    ["跑来", "pǎo lái", "come to", "datang ke"],
    ["捐款", "juān kuǎn", "donate", "derma"],
    ["。", "", "", ""],
    ["每次", "měi cì", "every time", "setiap kali"],
    ["，", "", "", ""],
    ["全校师生", "quán xiào shī shēng", "all teachers and students", "semua guru dan murid"],
    ["都会", "dōu huì", "will", "akan"],
    ["倾巢而出", "qīng cháo ér chū", "turn out in full force", "keluar berbondong-bondong"],
    ["：", "", "", ""],
    ["学生", "xué shēng", "students", "murid-murid"],
    ["站在", "zhàn zài", "stand on", "berdiri di"],
    ["山岭上", "shān lǐng shàng", "on the mountain ridge", "atas pergunungan"],
    ["，", "", "", ""],
    ["手舞", "shǒu wǔ", "waving", "melambai-lambai"],
    ["鲜花", "xiān huā", "flowers", "bunga"],
    ["一路", "yí lù", "along the way", "sepanjang jalan"],
    ["欢迎", "huān yíng", "welcome", "menyambut"],
    ["；", "", "", ""],
    ["而", "ér", "while", "manakala"],
    ["校长", "xiào zhǎng", "principal", "guru besar"],
    ["方子儒", "fāng zǐ rú", "Fang Ziru", "Fang Ziru"],
    ["会", "huì", "will", "akan"],
    ["亲自", "qīn zì", "personally", "sendiri"],
    ["带队", "dài duì", "lead the team", "mengetuai rombongan"],
    ["，", "", "", ""],
    ["用", "yòng", "use", "menggunakan"],
    ["一个", "yí gè", "a", "sebuah"],
    ["树藤", "shù téng", "rattan", "rotan"],
    ["扎成的", "zhā chéng de", "made of", "yang dibuat daripada"],
    ["土轿子", "tǔ jiào zi", "sedan chair", "usung"],
    ["抬", "tái", "carry", "usung"],
    ["客人", "kè rén", "guest", "tetamu"],
    ["上山", "shàng shān", "up the mountain", "naik gunung"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 2 段

    ["这天", "zhè tiān", "This day", "Pada hari ini"],
    ["，", "", "", ""],
    ["天堂村小学", "tiān táng cūn xiǎo xué", "Tiantang Village Primary School", "Sekolah Rendah Kampung Tiantang"],
    ["迎来了", "yíng lái le", "welcomed", "menyambut"],
    ["一个", "yí gè", "a", "seorang"],
    ["特别的", "tè bié de", "special", "istimewa"],
    ["客人", "kè rén", "guest", "tetamu"],
    ["。", "", "", ""],
    ["这个", "zhè ge", "this", "Ini"],
    ["年轻人", "nián qīng rén", "young man", "pemuda"],
    ["不声不响", "bù shēng bù xiǎng", "quietly", "secara senyap"],
    ["，", "", "", ""],
    ["独自", "dú zì", "alone", "bersendirian"],
    ["走了", "zǒu le", "walked", "berjalan"],
    ["两个小时", "liǎng gè xiǎo shí", "two hours", "dua jam"],
    ["的山路", "de shān lù", "mountain path", "jalan gunung"],
    ["。", "", "", ""],
    ["由于", "yóu yú", "because", "Oleh kerana"],
    ["道路", "dào lù", "road", "jalan"],
    ["崎岖", "qí qū", "rugged", "berbatu-batu"],
    ["，", "", "", ""],
    ["他", "tā", "he", "dia"],
    ["沿途", "yán tú", "along the way", "sepanjang perjalanan"],
    ["还", "hái", "also", "juga"],
    ["摔伤了", "shuāi shāng le", "fell and injured", "jatuh dan cedera"],
    ["膝盖", "xī gài", "knee", "lutut"],
    ["。", "", "", ""],
    ["当", "dāng", "when", "Apabila"],
    ["他", "tā", "he", "dia"],
    ["一瘸一拐地", "yī qué yī guǎi de", "limping", "terhincut-hincut"],
    ["出现在", "chū xiàn zài", "appeared at", "muncul di"],
    ["方子儒", "fāng zǐ rú", "Fang Ziru", "Fang Ziru"],
    ["面前时", "miàn qián shí", "in front of", "di hadapan"],
    ["，", "", "", ""],
    ["完全", "wán quán", "completely", "sama sekali"],
    ["没有了", "méi yǒu le", "no longer had", "tiada lagi"],
    ["城里人", "chéng lǐ rén", "city person", "orang bandar"],
    ["的", "de", "", ""],
    ["光鲜", "guāng xiān", "glamorous", "bergaya"],
    ["形象", "xíng xiàng", "image", "penampilan"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 3 段

    ["“", "", "", ""],
    ["对不起", "duì bù qǐ", "Sorry", "Maaf"],
    ["！", "", "", ""],
    ["”", "", "", ""],
    ["年轻人", "nián qīng rén", "The young man", "Pemuda itu"],
    ["显得", "xiǎn de", "seemed", "kelihatan"],
    ["有点", "yǒu diǎn", "a little", "agak"],
    ["尴尬", "gān gà", "awkward", "kekok"],
    ["，", "", "", ""],
    ["“", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["……", "", "", ""],
    ["想", "xiǎng", "want", "hendak"],
    ["资助", "zī zhù", "sponsor", "menaja"],
    ["你们", "nǐ men", "you all", "awak"],
    ["10", "shí", "ten", "sepuluh"],
    ["名", "míng", "measure word", "orang"],
    ["贫困生", "pín kùn shēng", "needy students", "pelajar miskin"],
    ["。", "", "", ""],
    ["”", "", "", ""],
    ["方子儒", "fāng zǐ rú", "Fang Ziru", "Fang Ziru"],
    ["特别", "tè bié", "especially", "sangat"],
    ["高兴", "gāo xìng", "happy", "gembira"],
    ["。", "", "", ""],
    ["这里", "zhè lǐ", "here", "Di sini"],
    ["是", "shì", "is", "ialah"],
    ["全县", "quán xiàn", "whole county", "seluruh daerah"],
    ["出了名的", "chū le míng de", "famous for", "terkenal sebagai"],
    ["贫困乡", "pín kùn xiāng", "poor township", "kampung miskin"],
    ["，", "", "", ""],
    ["这", "zhè", "this", "ini"],
    ["送上门", "sòng shàng mén", "come to the doorstep", "datang ke depan pintu"],
    ["的好事", "de hǎo shì", "good deed", "perkara baik"],
    ["，", "", "", ""],
    ["正", "zhèng", "just", "sedang"],
    ["求之不得", "qiú zhī bù dé", "most welcome", "sangat dialu-alukan"],
    ["呢", "ne", "particle", "!"],
    ["！", "", "", ""],
    ["可是", "kě shì", "but", "Tetapi"],
    ["，", "", "", ""],
    ["他", "tā", "he", "dia"],
    ["为什么", "wèi shén me", "why", "kenapa"],
    ["要说", "yào shuō", "would say", "hendak berkata"],
    ["对不起", "duì bù qǐ", "sorry", "maaf"],
    ["呢", "ne", "particle", "?"],
    ["？", "", "", ""],
    ["方子儒", "fāng zǐ rú", "Fang Ziru", "Fang Ziru"],
    ["殷勤地", "yīn qín de", "attentively", "dengan mesra"],
    ["招呼道", "zhāo hu dào", "greeted", "menyapa"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["要不", "yào bù", "how about", "bagaimana kalau"],
    ["，", "", "", ""],
    ["您", "nín", "you", "awak"],
    ["先", "xiān", "first", "dulu"],
    ["去", "qù", "go", "pergi"],
    ["洗漱", "xǐ shù", "wash up", "basuh"],
    ["一下", "yí xià", "a bit", "sebentar"],
    ["？", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["让", "ràng", "let", "suruh"],
    ["学生们", "xué shēng men", "students", "murid-murid"],
    ["列队", "liè duì", "line up", "berbaris"],
    ["欢迎", "huān yíng", "welcome", "menyambut"],
    ["？", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第 4 段

    ["年轻人", "nián qīng rén", "The young man", "Pemuda itu"],
    ["慌乱地", "huāng luàn de", "hurriedly", "dengan tergesa-gesa"],
    ["摆摆手", "bǎi bǎi shǒu", "waved his hand", "melambai tangan"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["千万不要", "qiān wàn bú yào", "Please don't", "Jangan"],
    ["……", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["不想", "bù xiǎng", "don't want", "tidak mahu"],
    ["耽搁", "dān ge", "delay", "melambatkan"],
    ["，", "", "", ""],
    ["捐了款", "juān le kuǎn", "donate the money", "derma"],
    ["就走", "jiù zǒu", "and leave", "dan pergi"],
    ["！", "", "", ""],
    ["”", "", "", ""],
    ["方子儒", "fāng zǐ rú", "Fang Ziru", "Fang Ziru"],
    ["点了点头", "diǎn le diǎn tóu", "nodded", "mengangguk"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 5 段

    ["15", "shí wǔ", "Fifteen", "Lima belas"],
    ["分钟后", "fēn zhōng hòu", "minutes later", "minit kemudian"],
    ["，", "", "", ""],
    ["方子儒", "fāng zǐ rú", "Fang Ziru", "Fang Ziru"],
    ["恭敬地", "gōng jìng de", "respectfully", "dengan hormat"],
    ["送上", "sòng shàng", "handed over", "menyerahkan"],
    ["一份", "yí fèn", "a", "satu"],
    ["资助名单", "zī zhù míng dān", "sponsorship list", "senarai penerima"],
    ["。", "", "", ""],
    ["年轻人", "nián qīng rén", "The young man", "Pemuda itu"],
    ["看", "kàn", "looked", "melihat"],
    ["也", "yě", "also", "pun"],
    ["没看", "méi kàn", "didn't look", "tidak melihat"],
    ["，", "", "", ""],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["校长", "xiào zhǎng", "Principal", "Guru besar"],
    ["，", "", "", ""],
    ["我想", "wǒ xiǎng", "I think", "saya rasa"],
    ["您", "nín", "you", "awak"],
    ["误会了", "wù huì le", "misunderstood", "salah faham"],
    ["！", "", "", ""],
    ["”", "", "", ""],
    ["方子儒", "fāng zǐ rú", "Fang Ziru", "Fang Ziru"],
    ["愣了愣", "lèng le lèng", "stunned", "terkejut"],
    ["，", "", "", ""],
    ["以为", "yǐ wéi", "thought", "fikir"],
    ["他", "tā", "he", "dia"],
    ["突然", "tū rán", "suddenly", "tiba-tiba"],
    ["变卦了", "biàn guà le", "changed his mind", "berubah fikiran"],
    ["，", "", "", ""],
    ["着急地", "zháo jí de", "anxiously", "dengan cemas"],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["可是", "kě shì", "but", "Tetapi"],
    ["，", "", "", ""],
    ["这", "zhè", "this", "ini"],
    ["是", "shì", "is", "ialah"],
    ["我们", "wǒ men", "we", "kami"],
    ["千挑万选", "qiān tiǎo wàn xuǎn", "carefully selected", "pilih-pilih"],
    ["出来的", "chū lái de", "selected", "yang terpilih"],
    ["学生", "xué shēng", "students", "murid"],
    ["。", "", "", ""],
    ["他们", "tā men", "they", "mereka"],
    ["品学兼优", "pǐn xué jiān yōu", "outstanding", "cemerlang"],
    ["，", "", "", ""],
    ["将来", "jiāng lái", "in the future", "pada masa depan"],
    ["一定", "yí dìng", "definitely", "pasti"],
    ["是", "shì", "are", "ialah"],
    ["国家", "guó jiā", "the nation's", "negara"],
    ["的", "de", "", ""],
    ["栋梁之材", "dòng liáng zhī cái", "pillars of the country", "harapan negara"],
    ["！", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第 6 段

    ["年轻人", "nián qīng rén", "The young man", "Pemuda itu"],
    ["沉默", "chén mò", "was silent", "diam"],
    ["了", "le", "", ""],
    ["一会儿", "yí huì er", "for a moment", "seketika"],
    ["，", "", "", ""],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["校长", "xiào zhǎng", "Principal", "Guru besar"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["能", "néng", "can", "boleh"],
    ["亲自", "qīn zì", "personally", "sendiri"],
    ["挑选", "tiāo xuǎn", "select", "pilih"],
    ["资助对象", "zī zhù duì xiàng", "beneficiaries", "penerima"],
    ["吗", "ma", "particle", "?"],
    ["？”", "", "", ""],
    ["“", "", "", ""],
    ["当然", "dāng rán", "Of course", "Tentu"],
    ["！", "", "", ""],
    ["”", "", "", ""],
    ["方子儒", "fāng zǐ rú", "Fang Ziru", "Fang Ziru"],
    ["长舒了", "cháng shū le", "breathed a sigh of", "menghembuskan nafas"],
    ["一口气", "yì kǒu qì", "relief", "lega"],
    ["，", "", "", ""],
    ["“", "", "", ""],
    ["这", "zhè", "this", "ini"],
    ["是", "shì", "is", "ialah"],
    ["您的", "nín de", "your", "awak punya"],
    ["权利", "quán lì", "right", "hak"],
    ["！", "", "", ""],
    ["但", "dàn", "but", "tetapi"],
    ["……", "", "", ""],
    ["他们", "tā men", "they", "mereka"],
    ["绝对", "jué duì", "absolutely", "pasti"],
    ["是", "shì", "are", "ialah"],
    ["最好的", "zuì hǎo de", "the best", "yang terbaik"],
    ["学生", "xué shēng", "students", "murid"],
    ["！", "", "", ""],
    ["倘若", "tǎng ruò", "if", "jika"],
    ["您", "nín", "you", "awak"],
    ["不信", "bù xìn", "don't believe", "tidak percaya"],
    ["，", "", "", ""],
    ["可以", "kě yǐ", "can", "boleh"],
    ["翻看", "fān kàn", "look through", "lihat"],
    ["他们", "tā men", "their", "mereka"],
    ["往年", "wǎng nián", "previous years'", "tahun-tahun lepas"],
    ["的", "de", "", ""],
    ["成绩单", "chéng jì dān", "report cards", "keputusan"],
    ["！", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第 7 段

    ["年轻人", "nián qīng rén", "The young man", "Pemuda itu"],
    ["笑了", "xiào le", "smiled", "tersenyum"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["当然", "dāng rán", "of course", "tentu"],
    ["相信", "xiāng xìn", "believe", "percaya"],
    ["，", "", "", ""],
    ["但", "dàn", "but", "tetapi"],
    ["请", "qǐng", "please", "tolong"],
    ["给", "gěi", "give", "beri"],
    ["我", "wǒ", "me", "saya"],
    ["所有", "suǒ yǒu", "all", "semua"],
    ["贫困生", "pín kùn shēng", "needy students", "pelajar miskin"],
    ["的", "de", "", ""],
    ["名单", "míng dān", "list", "senarai"],
    ["！", "", "", ""],
    ["”", "", "", ""],
    ["方子儒", "fāng zǐ rú", "Fang Ziru", "Fang Ziru"],
    ["虽然", "suī rán", "although", "walaupun"],
    ["感到", "gǎn dào", "felt", "berasa"],
    ["奇怪", "qí guài", "strange", "pelik"],
    ["，", "", "", ""],
    ["但", "dàn", "but", "tetapi"],
    ["还是", "hái shì", "still", "masih"],
    ["找来", "zhǎo lái", "found", "mendapatkan"],
    ["所有", "suǒ yǒu", "all", "semua"],
    ["30", "sān shí", "thirty", "tiga puluh"],
    ["名", "míng", "measure word", "orang"],
    ["贫困生", "pín kùn shēng", "needy students", "pelajar miskin"],
    ["的", "de", "", ""],
    ["名单", "míng dān", "list", "senarai"],
    ["。", "", "", ""],
    ["年轻人", "nián qīng rén", "The young man", "Pemuda itu"],
    ["要了", "yào le", "asked for", "meminta"],
    ["一张", "yì zhāng", "a", "sehelai"],
    ["白纸", "bái zhǐ", "white paper", "kertas putih"],
    ["，", "", "", ""],
    ["小心地", "xiǎo xīn de", "carefully", "dengan hati-hati"],
    ["撕成", "sī chéng", "tore into", "mengoyak menjadi"],
    ["一条条", "yì tiáo tiáo", "strips", "jalur-jalur"],
    ["小纸条", "xiǎo zhǐ tiáo", "small notes", "nota-nota kecil"],
    ["。", "", "", ""],
    ["然后", "rán hòu", "then", "kemudian"],
    ["，", "", "", ""],
    ["年轻人", "nián qīng rén", "the young man", "pemuda itu"],
    ["开始", "kāi shǐ", "began", "mula"],
    ["在", "zài", "on", "di"],
    ["小纸条上", "xiǎo zhǐ tiáo shàng", "on the small notes", "pada nota-nota kecil"],
    ["写上", "xiě shàng", "write", "menulis"],
    ["每一位", "měi yí wèi", "every", "setiap"],
    ["贫困生", "pín kùn shēng", "needy student", "pelajar miskin"],
    ["的", "de", "", ""],
    ["名字", "míng zi", "name", "nama"],
    ["，", "", "", ""],
    ["写完", "xiě wán", "finished writing", "selepas menulis"],
    ["一张", "yì zhāng", "one", "satu"],
    ["，", "", "", ""],
    ["就", "jiù", "then", "lalu"],
    ["揉成团", "róu chéng tuán", "crumpled into a ball", "remukkan menjadi bola"],
    ["丢", "diū", "throw", "buang"],
    ["在", "zài", "into", "ke dalam"],
    ["一个", "yí gè", "a", "sebuah"],
    ["盘子", "pán zi", "plate", "pinggan"],
    ["里", "lǐ", "inside", "dalam"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 8 段

    ["方子儒", "fāng zǐ rú", "Fang Ziru", "Fang Ziru"],
    ["终于", "zhōng yú", "finally", "akhirnya"],
    ["看出", "kàn chū", "saw", "nampak"],
    ["了", "le", "", ""],
    ["端倪", "duān ní", "the clue", "tanda-tanda"],
    ["，", "", "", ""],
    ["疑惑地", "yí huò de", "confusedly", "dengan hairan"],
    ["问道", "wèn dào", "asked", "bertanya"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["您", "nín", "you", "awak"],
    ["……", "", "", ""],
    ["是", "shì", "is", "ialah"],
    ["想", "xiǎng", "want", "hendak"],
    ["抓阄儿", "zhuā jiū ér", "draw lots", "buat undian"],
    ["决定", "jué dìng", "decide", "tentukan"],
    ["资助", "zī zhù", "sponsorship", "tajaan"],
    ["的", "de", "", ""],
    ["对象", "duì xiàng", "beneficiaries", "penerima"],
    ["？", "", "", ""],
    ["”", "", "", ""],
    ["年轻人", "nián qīng rén", "The young man", "Pemuda itu"],
    ["点了点头", "diǎn le diǎn tóu", "nodded", "mengangguk"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["是的", "shì de", "Yes", "Ya"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["觉得", "jué de", "think", "rasa"],
    ["那样", "nà yàng", "that way", "macam itu"],
    ["才", "cái", "only then", "baru"],
    ["公平", "gōng píng", "fair", "adil"],
    ["！", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第 9 段

    ["方子儒", "fāng zǐ rú", "Fang Ziru", "Fang Ziru"],
    ["着急地", "zháo jí de", "anxiously", "dengan cemas"],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["不行", "bù xíng", "No", "Tidak boleh"],
    ["，", "", "", ""],
    ["那样", "nà yàng", "that way", "macam itu"],
    ["你", "nǐ", "you", "awak"],
    ["会", "huì", "will", "akan"],
    ["不小心", "bù xiǎo xīn", "accidentally", "tidak sengaja"],
    ["抽到", "chōu dào", "draw", "tarik"],
    ["坏孩子", "huài hái zi", "bad children", "budak nakal"],
    ["的", "de", "", ""],
    ["。", "", "", ""],
    ["他们", "tā men", "they", "mereka"],
    ["生性", "shēng xìng", "by nature", "bersifat"],
    ["顽劣", "wán liè", "naughty and unruly", "nakal dan degil"],
    ["，", "", "", ""],
    ["整天", "zhěng tiān", "all day long", "sepanjang hari"],
    ["爬树", "pá shù", "climb trees", "panjat pokok"],
    ["打架", "dǎ jià", "fight", "bergaduh"],
    ["，", "", "", ""],
    ["几乎", "jī hū", "almost", "hampir"],
    ["每门", "měi mén", "every subject", "setiap mata pelajaran"],
    ["功课", "gōng kè", "subject", "mata pelajaran"],
    ["都", "dōu", "all", "semua"],
    ["不及格", "bù jí gé", "fail", "gagal"],
    ["！", "", "", ""],
    ["”", "", "", ""],
    ["年轻人", "nián qīng rén", "The young man", "Pemuda itu"],
    ["停下", "tíng xià", "stopped", "berhenti"],
    ["手中的笔", "shǒu zhōng de bǐ", "the pen in his hand", "pen di tangannya"],
    ["，", "", "", ""],
    ["问", "wèn", "asked", "bertanya"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["那", "nà", "then", "Kalau begitu"],
    ["他们", "tā men", "they", "mereka"],
    ["逃过学么", "táo guò xué me", "ever skipped school", "pernah ponteng sekolah"],
    ["？”", "", "", ""],
    ["方子儒", "fāng zǐ rú", "Fang Ziru", "Fang Ziru"],
    ["想了想", "xiǎng le xiǎng", "thought for a moment", "berfikir sejenak"],
    ["，", "", "", ""],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["这", "zhè", "this", "Ini"],
    ["……", "", "", ""],
    ["倒", "dào", "actually", "sebenarnya"],
    ["没有", "méi yǒu", "no", "tiada"],
    ["！", "", "", ""],
    ["他们", "tā men", "they", "mereka"],
    ["只是", "zhǐ shì", "just", "hanya"],
    ["功课", "gōng kè", "subjects", "mata pelajaran"],
    ["不好", "bù hǎo", "not good", "tidak bagus"],
    ["，", "", "", ""],
    ["其他的", "qí tā de", "other", "lain-lain"],
    ["没什么", "méi shén me", "nothing much", "tiada apa-apa"],
    ["两样", "liǎng yàng", "different", "perbezaan"],
    ["！", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第 10 段

    ["年轻人", "nián qīng rén", "The young man", "Pemuda itu"],
    ["坚定地", "jiān dìng de", "firmly", "dengan tegas"],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["在", "zài", "in", "Dalam"],
    ["我眼里", "wǒ yǎn lǐ", "my eyes", "pandangan saya"],
    ["，", "", "", ""],
    ["从来没有", "cóng lái méi yǒu", "never", "tidak pernah"],
    ["一个", "yí gè", "a", "seorang"],
    ["坏孩子", "huài hái zi", "bad child", "budak nakal"],
    ["，", "", "", ""],
    ["我们", "wǒ men", "we", "kita"],
    ["一样", "yí yàng", "equally", "sama-sama"],
    ["爱", "ài", "love", "sayangi"],
    ["他们", "tā men", "them", "mereka"],
    ["。", "", "", ""],
    ["谁", "shuí", "who", "Siapa"],
    ["又", "yòu", "again", "pula"],
    ["能", "néng", "can", "boleh"],
    ["知道", "zhī dào", "know", "tahu"],
    ["，", "", "", ""],
    ["调皮捣蛋", "tiáo pí dǎo dàn", "naughty", "nakal"],
    ["的孩子", "de hái zi", "children", "budak"],
    ["将来", "jiāng lái", "in the future", "pada masa depan"],
    ["就", "jiù", "then", "pasti"],
    ["一定", "yí dìng", "definitely", "pasti"],
    ["不会", "bù huì", "will not", "tidak akan"],
    ["有所作为", "yǒu suǒ zuò wéi", "achieve something", "berjaya"],
    ["呢", "ne", "particle", "?"],
    ["？", "", "", ""],
    ["他们", "tā men", "they", "mereka"],
    ["一样", "yí yàng", "equally", "sama-sama"],
    ["天真无邪", "tiān zhēn wú xié", "innocent and pure", "suci dan polos"],
    ["，", "", "", ""],
    ["他们的", "tā men de", "their", "mereka punya"],
    ["心里", "xīn lǐ", "hearts", "hati"],
    ["一样", "yí yàng", "equally", "sama-sama"],
    ["编织着", "biān zhī zhe", "weaving", "menenun"],
    ["最美丽的", "zuì měi lì de", "the most beautiful", "paling indah"],
    ["梦想", "mèng xiǎng", "dreams", "impian"],
    ["……", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第 11 段

    ["3", "sān", "Three", "Tiga"],
    ["分钟后", "fēn zhōng hòu", "minutes later", "minit kemudian"],
    ["，", "", "", ""],
    ["年轻人", "nián qīng rén", "the young man", "pemuda itu"],
    ["抽出了", "chōu chū le", "drew out", "tarik keluar"],
    ["10", "shí", "ten", "sepuluh"],
    ["个人的名字", "gè rén de míng zi", "names", "nama orang"],
    ["。", "", "", ""],
    ["果不其然", "guǒ bù qí rán", "as expected", "seperti yang dijangkakan"],
    ["，", "", "", ""],
    ["其中", "qí zhōng", "among them", "antaranya"],
    ["有", "yǒu", "there were", "ada"],
    ["4", "sì", "four", "empat"],
    ["名学生", "míng xué shēng", "students", "orang murid"],
    ["原本", "yuán běn", "originally", "pada asalnya"],
    ["不在", "bù zài", "not in", "tidak dalam"],
    ["方子儒", "fāng zǐ rú", "Fang Ziru's", "Fang Ziru"],
    ["的", "de", "", ""],
    ["推荐", "tuī jiàn", "recommendation", "cadangan"],
    ["之列", "zhī liè", "list", "senarai"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 12 段

    ["方子儒", "fāng zǐ rú", "Fang Ziru", "Fang Ziru"],
    ["执意", "zhí yì", "insisted", "berkeras"],
    ["要", "yào", "to", "hendak"],
    ["举行", "jǔ xíng", "hold", "mengadakan"],
    ["一个", "yí gè", "a", "sebuah"],
    ["公开的", "gōng kāi de", "public", "terbuka"],
    ["捐赠仪式", "juān zèng yí shì", "donation ceremony", "majlis derma"],
    ["，", "", "", ""],
    ["这是", "zhè shì", "this is", "ini ialah"],
    ["学校", "xué xiào", "school", "sekolah"],
    ["的", "de", "", ""],
    ["惯例", "guàn lì", "tradition", "kebiasaan"],
    ["。", "", "", ""],
    ["年轻人", "nián qīng rén", "The young man", "Pemuda itu"],
    ["却", "què", "however", "sebaliknya"],
    ["摇了摇头", "yáo le yáo tóu", "shook his head", "geleng kepala"],
    ["，", "", "", ""],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["校长", "xiào zhǎng", "Principal", "Guru besar"],
    ["，", "", "", ""],
    ["能否", "néng fǒu", "could you", "bolehkah"],
    ["替我", "tì wǒ", "for me", "untuk saya"],
    ["向", "xiàng", "to", "kepada"],
    ["其他的", "qí tā de", "the other", "yang lain"],
    ["20", "èr shí", "twenty", "dua puluh"],
    ["名学生", "míng xué shēng", "students", "orang murid"],
    ["道歉", "dào qiàn", "apologize", "minta maaf"],
    ["？", "", "", ""],
    ["”", "", "", ""],
    ["方子儒", "fāng zǐ rú", "Fang Ziru", "Fang Ziru"],
    ["满脸", "mǎn liǎn", "with a face full of", "dengan raut"],
    ["惊愕", "jīng è", "stunned", "terkejut"],
    ["，", "", "", ""],
    ["以为", "yǐ wéi", "thought", "fikir"],
    ["自己", "zì jǐ", "himself", "dirinya"],
    ["听错了", "tīng cuò le", "misheard", "salah dengar"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 13 段

    ["年轻人的", "nián qīng rén de", "The young man's", "Pemuda itu punya"],
    ["眼睛", "yǎn jīng", "eyes", "mata"],
    ["有些", "yǒu xiē", "somewhat", "agak"],
    ["湿润", "shī rùn", "moist", "basah"],
    ["，", "", "", ""],
    ["满怀歉意地", "mǎn huái qiàn yì de", "full of apology", "dengan penuh penyesalan"],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["对不起", "duì bù qǐ", "I'm sorry", "Maaf"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["没有", "méi yǒu", "don't have", "tidak ada"],
    ["能力", "néng lì", "ability", "kemampuan"],
    ["资助", "zī zhù", "sponsor", "menaja"],
    ["所有", "suǒ yǒu", "all", "semua"],
    ["的", "de", "", ""],
    ["贫困生", "pín kùn shēng", "needy students", "pelajar miskin"],
    ["。", "", "", ""],
    ["他们", "tā men", "they", "mereka"],
    ["之所以", "zhī suǒ yǐ", "the reason why", "sebabnya"],
    ["没被选上", "méi bèi xuǎn shàng", "not selected", "tidak terpilih"],
    ["，", "", "", ""],
    ["并不是", "bìng bú shì", "not because", "bukan kerana"],
    ["因为", "yīn wèi", "because", "kerana"],
    ["不够好", "bù gòu hǎo", "not good enough", "tidak cukup baik"],
    ["，", "", "", ""],
    ["只是", "zhǐ shì", "just", "hanya"],
    ["运气", "yùn qì", "luck", "nasib"],
    ["差了", "chà le", "worse", "kurang baik"],
    ["一些", "yì xiē", "a little", "sedikit"],
    ["！", "", "", ""],
    ["总有一天", "zǒng yǒu yì tiān", "one day", "Suatu hari nanti"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["会", "huì", "will", "akan"],
    ["回来", "huí lái", "come back", "kembali"],
    ["弥补", "mí bǔ", "make up for", "pampasan"],
    ["他们的", "tā men de", "their", "mereka punya"],
    ["遗憾", "yí hàn", "regret", "penyesalan"],
    ["！", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第 14 段

    ["年轻人", "nián qīng rén", "The young man", "Pemuda itu"],
    ["没有", "méi yǒu", "did not", "tidak"],
    ["告诉", "gào su", "tell", "memberitahu"],
    ["校长", "xiào zhǎng", "the principal", "guru besar"],
    ["，", "", "", ""],
    ["在", "zài", "in", "Pada"],
    ["15", "shí wǔ", "fifteen", "lima belas"],
    ["年前", "nián qián", "years ago", "tahun yang lalu"],
    ["的", "de", "", ""],
    ["一个", "yí gè", "a", "sebuah"],
    ["穷山沟", "qióng shān gōu", "poor mountain village", "kampung miskin"],
    ["，", "", "", ""],
    ["他", "tā", "he", "dia"],
    ["也是", "yě shì", "also", "juga"],
    ["这样", "zhè yàng", "like this", "begitu"],
    ["幸运地", "xìng yùn de", "luckily", "dengan bernasib baik"],
    ["得到", "dé dào", "received", "mendapat"],
    ["一位", "yí wèi", "a", "seorang"],
    ["老华侨", "lǎo huá qiáo", "elderly overseas Chinese", "orang tua Cina di perantauan"],
    ["的", "de", "", ""],
    ["捐助", "juān zhù", "donation", "sumbangan"],
    ["。", "", "", ""],
    ["当时", "dāng shí", "at that time", "Pada masa itu"],
    ["，", "", "", ""],
    ["他", "tā", "he", "dia"],
    ["是", "shì", "was", "ialah"],
    ["村民", "cūn mín", "villagers'", "penduduk kampung"],
    ["眼中", "yǎn zhōng", "in the eyes of", "dalam pandangan"],
    ["不折不扣", "bù zhé bù kòu", "out-and-out", "betul-betul"],
    ["的", "de", "", ""],
    ["坏孩子", "huài hái zi", "bad kid", "budak nakal"],
    ["。", "", "", ""],
    ["可是", "kě shì", "but", "Tetapi"],
    ["，", "", "", ""],
    ["老华侨", "lǎo huá qiáo", "the elderly overseas Chinese", "orang tua Cina itu"],
    ["的", "de", "", ""],
    ["一句话", "yí jù huà", "one sentence", "satu ayat"],
    ["改变了", "gǎi biàn le", "changed", "mengubah"],
    ["他", "tā", "his", "dia punya"],
    ["的一生", "de yì shēng", "life", "hidup"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["在我眼里", "zài wǒ yǎn lǐ", "In my eyes", "Dalam pandangan saya"],
    ["，", "", "", ""],
    ["从来没有", "cóng lái méi yǒu", "never", "tidak pernah"],
    ["一个", "yí gè", "a", "seorang"],
    ["坏孩子", "huài hái zi", "bad child", "budak nakal"],
    ["，", "", "", ""],
    ["我们", "wǒ men", "we", "kita"],
    ["一样", "yí yàng", "equally", "sama-sama"],
    ["爱", "ài", "love", "sayangi"],
    ["他们", "tā men", "them", "mereka"],
    ["！", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 出处

    ["（", "", "", ""],
    ["张春风", "zhāng chūn fēng", "Zhang Chunfeng", "Zhang Chunfeng"],
    ["《", "", "", ""],
    ["我们一样爱他们", "wǒ men yí yàng ài tā men", "We Love Them Equally", "Kita Sama Sayangi Mereka"],
    ["》", "", "", ""],
    ["，", "", "", ""],
    ["有", "yǒu", "with", "ada"],
    ["改动", "gǎi dòng", "adaptations", "ubah suai"],
    ["）", "", "", ""]
];
